server:
  port: 9010
spring:
  application:
      name: service-product
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productBD;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTER:-%5p}} %m%n"